AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template to deploy a lambda which is triggered by an S3 event.

Parameters:
  DeploymentBucket:
    Type: String
    Description: Enter the name of the S3 bucket where your deployment package is.
    Default: team1-testbucket
  DeploymentPackageKey:
    Type: String
    Description: Enter the name of the S3 key of your deployment package.
    Default: lambdacode.zip
  S3BucketName:
    Type: String
    Description: Enter name of the S3 data bucket
    Default: delee3-Team1-testbucket



Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonRedshiftDataFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Policies:
      - PolicyName: LambdaLogsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource: '*'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: ETL lambda function team 1
      Timeout: 30
      FunctionName: team1ETL
      Runtime: python3.9
      Handler: lambda_handler.handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Layers: [arn:aws:lambda:eu-west-1:239598709205:layer:SQLAlchemy:1, arn:aws:lambda:eu-west-1:239598709205:layer:python_39_psycopg2_layer:1, arn:aws:lambda:eu-west-1:239598709205:layer:Team1-reqsV2:3]
      Code:
          S3Bucket: !Ref DeploymentBucket
          S3Key: !Ref DeploymentPackageKey

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
    DependsOn: S3BucketPermission
    Properties:
    BucketName: !Ref S3BucketName
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: csv
              Function: !GetAtt LambdaFunction.Arn

  S3BucketPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt S3Bucket.Arn

