version: "3.8"
services:
  db:
    image: postgres:10.5
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "database"
    ports:
      - "5432:5432"
    
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
