version: "3.8"
services:
  db:
    image: postgres:10.5
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "3306:3306"
    
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
