version: "3.8"
services:
  db:
    image: postgres
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRES_PASSWORD: "${postgres_pass}"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080